<a href="https://colab.research.google.com/github/Gabobooooooo/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Activity_3_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 3: Matrix Operations

#####Objectives
At the end of this activity you will be able to:

Be familiar with the fundamental matrix operations.

1.   Be familiar with the fundamental matrix operations.
2.   Apply the operations to solve intemrediate equations.
3.   Apply matrix algebra in engineering solutions.



In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#Transposition

#####One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. Let A = original value of the matrix A and A^T = transpose form of matrix a

$$A = \begin{bmatrix} 123 & 345 & 678\\910 & 11 &12 \\ 13 & 14 & 15\end{bmatrix} $$


$$A^T = \begin{bmatrix} 123 & 910 & 13\\345 & 11 &14 \\ 678 & 12 & 15\end{bmatrix} $$

In [2]:
A = np.array([
    [12 ,23, 45],
    [65, 71, 80],
    [90, -13, 23]
])
A

array([[ 12,  23,  45],
       [ 65,  71,  80],
       [ 90, -13,  23]])

In [ ]:
ATpose2 = np.transpose(A)
ATpose2

array([[ 12,  65,  90],
       [ 23,  71, -13],
       [ 45,  80,  23]])

In [ ]:
ATpose1 = A.T
ATpose1

array([[ 12,  65,  90],
       [ 23,  71, -13],
       [ 45,  80,  23]])

In [ ]:
np.array_equiv(ATpose1, ATpose2)

True

In [ ]:
Bmt = np.array([
    [6,6,6],
    [1,3,4],
])
Bmt.shape

(2, 3)

In [ ]:
np.transpose(Bmt).shape

(3, 2)

In [ ]:
BTpose = Bmt.T.shape
BTpose

(3, 2)

#Dot Product/Inner Product

######If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. Assign values for variable A and B

$$
A=\begin{bmatrix} 3 & 5 \\ 6 & 50\end{bmatrix},
B=\begin{bmatrix} 64 & 32 \\  23 & 5\end{bmatrix}\\
$$

$$
A ⋅ B=\begin{bmatrix} |3 * 64 + 5 * 23||3 * 32 + 5*5|\\ |6 *64 + 50*23| |6 * 32 + 50*5|\end{bmatrix} = \begin{bmatrix} 307&121 \\384&192\end{bmatrix}
$$

In [ ]:
Xmt = np.array([
    [16,22,44],
    [26,28,55],
    [62,82,77]
])
Ymt = np.array([
    [4,7,66],
    [22,19,22],
    [24,76,89]
])

In [ ]:
np.dot(Xmt,Ymt)

array([[ 1604,  3874,  5456],
       [ 2040,  4894,  7227],
       [ 3900,  7844, 12749]])

In [ ]:
Xmt.dot(Ymt)

array([[ 1604,  3874,  5456],
       [ 2040,  4894,  7227],
       [ 3900,  7844, 12749]])

In [ ]:
Xmt @ Ymt

array([[ 1604,  3874,  5456],
       [ 2040,  4894,  7227],
       [ 3900,  7844, 12749]])

In [ ]:
np.matmul(Xmt,Ymt)

array([[ 1604,  3874,  5456],
       [ 2040,  4894,  7227],
       [ 3900,  7844, 12749]])

###Rule 1: The inner dimensions of the two matrices in question must be the same

#####So given a matrix  with a shape of  where  and  are any integers. If we want to do a dot product between  and another matrix , then matrix  should have a shape of  where  and  are any integers. Let A, B, and C 

#####$$
A=\begin{bmatrix} 1 & 6 \\ 2 & 6\\ 2 & 6\end{bmatrix},
B=\begin{bmatrix} 132 & 2 \\  32 & 334\\\ 23 & 123\end{bmatrix}\\,
C=\begin{bmatrix} 23 & 32 & 12 \\  67 & 23 & 23\end{bmatrix}\\
$$

In [ ]:
A = np.array([
    [1, 6],
    [2,6 ],
    [2, 8]
])
B = np.array([
    [132,2],
    [32,334],
    [23,123,]
])
C = np.array([
    [23,32,12],
    [67,23,23]
    
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ B

ValueError: ignored

In [ ]:
B @ A

ValueError: ignored

#####When we try to multiply Matrix A to Matrix B, the result is error since our resulting matrix does not to the desired shape of (a,c) that is derived from A(a,b) and B(b,c)

In [ ]:
B.T @ A

array([[ 242, 1168],
       [ 916, 3000]])

#####As we tranpose Matrix B, errors are not found since it does now fit to the desired shape of (a,c) 

In [ ]:
A @ C

array([[425, 170, 150],
       [448, 202, 162],
       [582, 248, 208]])

In [ ]:
X = np.array([
    [87,65,43,21],
    [12,23,45,56]
])
Y = np.array([
    [11,22,33,44],
    [77,88,99,11]
])
print(X.shape)
print(Y.shape)

(2, 4)
(2, 4)


###Rule 2: Dot Product has special properties

#####Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions. Designate values for matrices A, B, and C.

In [ ]:
A = np.array([
    [6,6,6],
    [1,2,3],
    [5,5,5]
])
B = np.array([
    [11,12,13],
    [16,15,14],
    [23,22,21]
])
C = np.array([
    [55,66,77],
    [67,23,25],
    [62,10,90]
])

####First Property
A ⋅ B ≠ B ⋅ A

In [ ]:
AmultiB = A @ B
AmultiB

array([[300, 294, 288],
       [112, 108, 104],
       [250, 245, 240]])

In [ ]:
BmultiA = B @ A
BmultiA

array([[143, 155, 167],
       [181, 196, 211],
       [265, 287, 309]])

In [ ]:
np.array_equal(AmultiB,BmultiA)

False

####Second Property
A ⋅ (B⋅C) = (A⋅B) ⋅ C

In [ ]:
BmultiC = B @ C
BmultiC

array([[2215, 1132, 2317],
       [2753, 1541, 2867],
       [4041, 2234, 4211]])

In [ ]:
Left = A @ BmultiC
Left

array([[54054, 29442, 56370],
       [19844, 10916, 20684],
       [45045, 24535, 46975]])

In [ ]:
Right = AmultiB @ C
Right

array([[54054, 29442, 56370],
       [19844, 10916, 20684],
       [45045, 24535, 46975]])

In [ ]:
np.array_equal(Left,Right)

True

####Third Property
A ⋅ (B+C) = A⋅B + A⋅C


In [ ]:
BplusC = B + C
BplusC

array([[ 66,  78,  90],
       [ 83,  38,  39],
       [ 85,  32, 111]])

In [ ]:
AmultiC = A @ C
AmultiC

array([[1104,  594, 1152],
       [ 375,  142,  397],
       [ 920,  495,  960]])

In [ ]:
AmultiBlusC= A @ BplusC
AmultiBlusC

array([[1404,  888, 1440],
       [ 487,  250,  501],
       [1170,  740, 1200]])

In [ ]:
AmultiBplusAmultiC = AmultiB + AmultiC
AmultiBplusAmultiC

array([[1404,  888, 1440],
       [ 487,  250,  501],
       [1170,  740, 1200]])

In [ ]:
np.array_equal(AmultiBlusC,AmultiBplusAmultiC)

True

####Fourth Property
(B+C) ⋅ A = B⋅A + C⋅A

In [ ]:
Left4th = BplusC @ A
Left4th

array([[ 924, 1002, 1080],
       [ 731,  769,  807],
       [1097, 1129, 1161]])

In [ ]:
Right4th = (B @ A) + (C @ A)
Right4th

array([[ 924, 1002, 1080],
       [ 731,  769,  807],
       [1097, 1129, 1161]])

In [ ]:
np.array_equal(Left4th,Right4th)

True

####Fifth Property
A ⋅ I = A

In [ ]:
identmat = np.identity(3)
identmat


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Proof5th = A @ identmat
Proof5th

array([[6., 6., 6.],
       [1., 2., 3.],
       [5., 5., 5.]])

In [ ]:
np.array_equal(A,Proof5th)

True

####Sixth Property
A ⋅ 0 = 0

In [ ]:
Zeromat = np.zeros((3,3))
Zeromat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Proof6th = A @ Zeromat
Proof6th

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(Zeromat,Proof6th)

True

#Determinant

#####A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

In [ ]:
A = np.array([
    [69,14],
    [2001,143],
   
])
np.linalg.det(A)

-18147.000000000007

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [67,68,70,72],
    [89,23,53,76],
    [23,65,54,33],
    [88,30,11,32]
])
np.linalg.det(B)


1865950.9999999984

#Inverse

#####The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

In [ ]:
M = np.array([
    [55,66],
    [-88, 23]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
N = np.array([
    [33,45,35,23,52,32,55],
    [94,90,88,99,77,53,25],
    [45,28,22,12,23,89,75],
    [34,56,88,80,29,22,25],
    [84,23,55,63,23,83,28],
    [-34,75,95,63,23,95,-22],
    [-33,-28,12,26,10,90,22],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
squad = np.array([
    [8.0, 2.0, 6.5],
    [2.7, 8.7, 9.9],
    [2.3, 8.3, 1.5]
])
weights = np.array([
    [9.2, 0.7, 8.6]
])
p_grade = squad @ weights.T
p_grade

array([[130.9 ],
       [116.07],
       [ 39.87]])