<a href="https://colab.research.google.com/github/Gabobooooooo/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3_Roxas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Assignment 2 : Matrices

###Objectives

#####At the end of this activity, you will be able to:


*   Be familiar with matrices and their relation to linear equations
*   Perform basic matrix operations
*  Program and translate matrix equations and operations using Python.








#Discussion


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


#Matrices


######Let's say for example you have A and B as C system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\ 
        3w-x-2y+z \\
        2w-x+3y-2z
    \end{array}
\right. \\
$$

 
 
 
We could see that A is a system of 2 equations with 2 parameters, B has a system of 3 equations with 3 parameters, and C does also have 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & -10 \end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}\\
$$


#Declaring Matrices

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
def describe_mt(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [ ]:
A = np.array([
    [42, 28],
    [69, 5]
])
describe_mt(A)

Matrix:
[[42 28]
 [69  5]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [34,7,43],
    [99,23,26]
])
describe_mt(G)


Matrix:
[[34  7 43]
 [99 23 26]]

Shape:	(2, 3)
Rank:	2



In [ ]:
B = np.array([
    [32, 31],
    [533, 43],
    [500, 700]
])
describe_mt(B)


Matrix:
[[ 32  31]
 [533  43]
 [500 700]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([
  [69,21,23,4]
  ])
    
describe_mt(H)


Matrix:
[[69 21 23  4]]

Shape:	(1, 4)
Rank:	2



#Categorizing Matrices

#####Matrices are portrayed differently depending either on the shape or element values they contain.

##According to Shape

###Row and Columns


In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    5, 2, 7, -26
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [69,66,23, -56]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[  5   2   7 -26]

Shape:	(4,)
Rank:	1

Matrix:
[[ 69  66  23 -56]]

Shape:	(1, 4)
Rank:	2



In [ ]:
col_mat = np.array([
    [69],
    [16],
    [143]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[ 69]
 [ 16]
 [143]]

Shape:	(3, 1)
Rank:	2



###Square Matrix

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [1,4,3],
    [6,6,6],
    [7,7,7]
])

non_square_mat = np.array([
    [143,666,777],
    [1,4,3]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[1 4 3]
 [6 6 6]
 [7 7 7]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[143 666 777]
 [  1   4   3]]

Shape:	(2, 3)
Rank:	2
Is Square: False



#According to element values


###Null Matrix


In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


###Zero Matrix

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


###Ones Matrix

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


###Diagonal Matrix

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])


array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,3,5,7])
d


array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

###Identity Matrix

In [ ]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

###Upper Triangular Matrix


In [ ]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

###Lower Triangular Matrix

In [ ]:
np.tril(F)


array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

#Practice


####1.Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 6x + 12y - z$$

In [ ]:
Theta = np.array([
    [6,12,-1],
  
])

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
B = \left\{\begin{array}
4x_3 + 2x_2 + x_1\\
9x_3 - 5x_2 + 4x_1\\
60x_3 + 6x_2 + 5x_1
\end{array}\right.
$$


In [ ]:
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is a square matrix')
    else:
        print('The matrix is a non-square matrix')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is a ones matrix')
    else:
        print('The matrix is not a ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is a zeros matrix')
    else:
      print('The matrix is not a zeros matrix')

In [ ]:
print ('Matrix 10:')
RM10 = np.array([
    [1,2,1],
    [9,-5,4],
    [60,6,5]])

mat_desc(RM10)

Matrix 10:
[[ 1  2  1]
 [ 9 -5  4]
 [60  6  5]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is not a zeros matrix


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown



In [ ]:
B = np.array([
    [0,4,7],
    [3,4,9],
    [123,32,321]
])


$$
B = \left\{\begin{array}
6x_3 + 4x_2 + 7x_1\\
3x_3 + 4x_2 + 9x\\
123x_3 + 32x_2 + 321x
\end{array}\right.
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


$$
H = \left\{\begin{array}
6x_3 + 0x_2 + 0x_1\\
3x_3 + 4x_2 + 0x_1\\
123x_3 + 32x_2 + 321x1
\end{array}\right.
$$

In [ ]:
H = np.tril(G)
H


array([[  6,   0,   0],
       [  3,   4,   0],
       [123,  32, 321]])

#Matrix Algebra

####Addition


In [ ]:
A = np.array([
    [6,7],
    [5,9],
    [5,3]
])
B = np.array([
    [3,1],
    [9,3],
    [2,9]
])
A+B

array([[ 9,  8],
       [14, 12],
       [ 7, 12]])

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A


array([[ 8,  9],
       [ 7, 11],
       [ 7,  5]])

####Subtraction


In [ ]:
A-B

array([[ 3,  6],
       [-4,  6],
       [ 3, -6]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

####Elementary-wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

array([[18,  7],
       [45, 27],
       [10, 27]])

In [ ]:
2*A

array([[12, 14],
       [10, 18],
       [10,  6]])

In [ ]:

A@B

ValueError: ignored

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[2.        , 7.        ],
       [0.55555556, 3.        ],
       [2.5       , 0.33333333]])

In [ ]:
np.add(A,B)

array([[ 9,  8],
       [14, 12],
       [ 7, 12]])

#Activity

####Task1

#####Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix. Displays whether the matrix is square or non-square. Displays whether the matrix is an empty matrix. Displays if the matrix is an identity, ones, or zeros matrix Use 5 sample matrices in which their shapes are not lower than(3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is a square matrix')
    else:
        print('The matrix is a non-square matrix')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is a ones matrix')
    else:
        print('The matrix is not a ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is a zeros matrix')
    else:
      print('The matrix is not a zeros matrix')

In [ ]:
print ('Matrix 1:')
RM1 = np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]])

mat_desc(RM1)

Matrix 1:
[[1 0 0]
 [5 3 0]
 [7 8 5]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is not a zeros matrix


In [ ]:
print ('Matrix 2:')
RM2 = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]])

mat_desc(RM2)

Matrix 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (3, 3)
Size: 9
Rank: 0
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is a zeros matrix


In [ ]:
print ('Matrix 3:')
RM3 = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]])

mat_desc(RM3)

Matrix 3:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (3, 3)
Size: 9
Rank: 1
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is a ones matrix
The matrix is not a zeros matrix


In [ ]:
print ('Matrix 4:')
RM4 = np.array([
    [7,12,3],
    [12,32,51],
    [32,51,13]])

mat_desc(RM4)

Matrix 4:
[[ 7 12  3]
 [12 32 51]
 [32 51 13]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is not a zeros matrix


In [ ]:
print ('Matrix 5:')
RM5 = np.array ([
    [69,32,34],
    [134,66,16],
    [26,2001,2000]])

mat_desc(RM5)

Matrix 5:
[[  69   32   34]
 [ 134   66   16]
 [  26 2001 2000]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is not a zeros matrix


#Task 2

#####Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable. Returns the sum of the matrices. Returns the differen of the matrices. Returns the element-wise multiplication of the matrices. Returns the element-wise division of the matrices. Use 5 sample matrices in which their shapes are not lower than(3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The shape of both matrices are not the same. Could not perform operations.')
        return
    print('Sum of the given matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the given matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-wise multiplication of the matrices:')
    mmul = np.multiply(mat1, mat2)
    print(mmul)
    print('Element-wise division of the matrices:')
    mmul = np.divide(mat1, mat2)
    print(mmul)

In [ ]:
print('Sample Case: 1')
mat_operations([[7, 12, 3], [12, 32, 51], [32, 51, 13]], [[7, 12, 3], [12, 3, 5], [2, 1, 1]])
print('Sample Case: 2')
mat_operations([[7, 2, 3], [2, 2, 1], [2, 1, 3]], [[8, 2, 7], [2, 3, 5], [2 , 1, 1]])
print('Sample Case: 3')
mat_operations([[7, 2, 3], [12, 2, 1], [3, 1, 13]], [[7, 1, 2, 3], [1, 2, 3, 5], [0, 7, 3, 5], [2, 1, 1, 4]])
print('Sample Case: 4')
mat_operations([[0, 0, 0], [2, 0, 1], [0, 1, 3]], [[1, 0, 0], [2, 3, 5], [0, 0, 1]])
print('Sample Case: 5')
mat_operations([[7, 1, 2, 3], [1, 2, 3, 5], [0, 7, 3, 5]], [[7, 2, 3], [12, 2, 1], [3, 1, 13]])

Sample Case: 1
Matrix 1: [[ 7 12  3]
 [12 32 51]
 [32 51 13]]
Matrix 2: [[ 7 12  3]
 [12  3  5]
 [ 2  1  1]]
Sum of the given matrices:
[[14 24  6]
 [24 35 56]
 [34 52 14]]
Difference of the given matrices:
[[ 0  0  0]
 [ 0 29 46]
 [30 50 12]]
Element-wise multiplication of the matrices:
[[ 49 144   9]
 [144  96 255]
 [ 64  51  13]]
Element-wise division of the matrices:
[[ 1.          1.          1.        ]
 [ 1.         10.66666667 10.2       ]
 [16.         51.         13.        ]]
Sample Case: 2
Matrix 1: [[7 2 3]
 [2 2 1]
 [2 1 3]]
Matrix 2: [[8 2 7]
 [2 3 5]
 [2 1 1]]
Sum of the given matrices:
[[15  4 10]
 [ 4  5  6]
 [ 4  2  4]]
Difference of the given matrices:
[[-1  0 -4]
 [ 0 -1 -4]
 [ 0  0  2]]
Element-wise multiplication of the matrices:
[[56  4 21]
 [ 4  6  5]
 [ 4  1  3]]
Element-wise division of the matrices:
[[0.875      1.         0.42857143]
 [1.         0.66666667 0.2       ]
 [1.         1.         3.        ]]
Sample Case: 3
Matrix 1: [[ 7  2  3]
 [12  2  1]
 [ 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide
